name: down
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.4.0
  firebase_core: ^0.4.0
  cloud_firestore: ^0.13.4+2
  firebase_messaging: ^4.0.0+1
  firebase_storage: ^3.1.5
  firebase_auth: ^0.16.0
  firebase_database: ^3.1.3
  normal: ^0.5.1
  image: ^2.0.7
  animator: 0.1.4
  url_launcher: ^5.4.10
  charts_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/DownLogo.png
    - assets/images/phoneIcon.png
    - assets/images/launch_icon.png

